
import java.awt.Color;
import java.awt.event.KeyEvent;
import java.sql.*;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author iangk
 */
public class MyPage extends javax.swing.JFrame {

    Connection conn;
    ResultSet rs;
    PreparedStatement pst;

    String Months[] = {"January", "February", "March", "April", "May", "June", "July", "August", "September", "Octaber", "November", "December"};
    
    Color myColor = new Color(204, 204, 204);

    /**
     * Creates new form MyPage
     */
    public MyPage() {
        super("Home");
        initComponents();
        DBConnect obj = new DBConnect();
        conn = obj.openConnection();
        Calender();
    }

    public void Calender() {
        Calendar calender = new GregorianCalendar();
        int month = calender.get(Calendar.MONTH);
        int year = calender.get(Calendar.YEAR);
        int day = calender.get(Calendar.DAY_OF_MONTH);
        jTextField_Date.setText(+day + " " + Months[month] + ", " + year);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField_Date = new javax.swing.JTextField();
        jTabbedPane = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel_Profile = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField_DateOfBirth = new javax.swing.JTextField();
        jTextField_Name = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField_Gender = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jTextField_Address = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextField_Mobile = new javax.swing.JTextField();
        jTextField_NID = new javax.swing.JTextField();
        jTextField_AccountType = new javax.swing.JTextField();
        jTextField_AccountNo = new javax.swing.JTextField();
        jButton_Edit = new javax.swing.JButton();
        jButton_Save = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField_ProfileUserSearch = new javax.swing.JTextField();
        jButton_ProfileUserSearch = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTextField_DepositeAmount = new javax.swing.JTextField();
        jTextField_DepositeAvailableBalance = new javax.swing.JTextField();
        jTextField_DepositeAccountNo = new javax.swing.JTextField();
        jTextField_DepositeName = new javax.swing.JTextField();
        jButton_DepositeTotal = new javax.swing.JButton();
        jTextField_DepositeTotal = new javax.swing.JTextField();
        jButton_Deposite = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jTextField_DepositeUserSearch = new javax.swing.JTextField();
        jButton_DepositeUserSearch = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jTextField_TransferUserSearch = new javax.swing.JTextField();
        jButton_TransferUserSearch = new javax.swing.JButton();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jTextField_TransferAmount = new javax.swing.JTextField();
        jTextField_TransferAvailableBalance = new javax.swing.JTextField();
        jTextField_TransferAccountNo = new javax.swing.JTextField();
        jTextField_TransferName = new javax.swing.JTextField();
        jTextField_TransferTotal = new javax.swing.JTextField();
        jButton_TransferTotal = new javax.swing.JButton();
        jButton_Transfer = new javax.swing.JButton();
        jLabel22 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField_TransferTotal1 = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 51, 51));
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("eBanking");

        jLabel2.setText("Date:");

        jTextField_Date.setEditable(false);

        jTabbedPane.setForeground(new java.awt.Color(0, 51, 51));
        jTabbedPane.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jTabbedPane.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTabbedPane.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jTabbedPane.setMinimumSize(new java.awt.Dimension(680, 40));

        jPanel_Profile.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 51), 2));
        jPanel_Profile.setPreferredSize(new java.awt.Dimension(600, 269));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Address:");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("Name:");

        jTextField_DateOfBirth.setEditable(false);
        jTextField_DateOfBirth.setBackground(new java.awt.Color(204, 204, 204));
        jTextField_DateOfBirth.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jTextField_Name.setEditable(false);
        jTextField_Name.setBackground(new java.awt.Color(204, 204, 204));
        jTextField_Name.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Gender:");

        jTextField_Gender.setEditable(false);
        jTextField_Gender.setBackground(new java.awt.Color(204, 204, 204));
        jTextField_Gender.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Date Of Birth:");

        jTextField_Address.setEditable(false);
        jTextField_Address.setBackground(new java.awt.Color(204, 204, 204));
        jTextField_Address.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("Account No:");

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Account Type:");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("NID:");

        jLabel13.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel13.setText("Mobile:");

        jTextField_Mobile.setEditable(false);
        jTextField_Mobile.setBackground(new java.awt.Color(204, 204, 204));
        jTextField_Mobile.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jTextField_NID.setEditable(false);
        jTextField_NID.setBackground(new java.awt.Color(204, 204, 204));
        jTextField_NID.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jTextField_AccountType.setEditable(false);
        jTextField_AccountType.setBackground(new java.awt.Color(204, 204, 204));
        jTextField_AccountType.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jTextField_AccountNo.setEditable(false);
        jTextField_AccountNo.setBackground(new java.awt.Color(204, 204, 204));
        jTextField_AccountNo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jButton_Edit.setText("Edit");
        jButton_Edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_EditActionPerformed(evt);
            }
        });

        jButton_Save.setText("Save");
        jButton_Save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_SaveActionPerformed(evt);
            }
        });

        jLabel1.setText("Account No:");

        jButton_ProfileUserSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Eye.png"))); // NOI18N
        jButton_ProfileUserSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_ProfileUserSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel_ProfileLayout = new javax.swing.GroupLayout(jPanel_Profile);
        jPanel_Profile.setLayout(jPanel_ProfileLayout);
        jPanel_ProfileLayout.setHorizontalGroup(
            jPanel_ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ProfileLayout.createSequentialGroup()
                .addContainerGap(26, Short.MAX_VALUE)
                .addGroup(jPanel_ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_ProfileLayout.createSequentialGroup()
                        .addGroup(jPanel_ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel_ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_Address, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_Gender, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_DateOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_Name, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel_ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel13)
                            .addComponent(jLabel10)
                            .addComponent(jLabel12))
                        .addGap(23, 23, 23)
                        .addGroup(jPanel_ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_Mobile, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_AccountType, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_AccountNo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_NID, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_ProfileLayout.createSequentialGroup()
                        .addComponent(jButton_Edit)
                        .addGap(18, 18, 18)
                        .addComponent(jButton_Save)
                        .addGap(229, 229, 229))))
            .addGroup(jPanel_ProfileLayout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jTextField_ProfileUserSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton_ProfileUserSearch)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel_ProfileLayout.setVerticalGroup(
            jPanel_ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel_ProfileLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel_ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton_ProfileUserSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel_ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jTextField_ProfileUserSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(jPanel_ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_ProfileLayout.createSequentialGroup()
                        .addGroup(jPanel_ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(jTextField_AccountNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel_ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel12)
                            .addComponent(jTextField_AccountType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel_ProfileLayout.createSequentialGroup()
                        .addGroup(jPanel_ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(jTextField_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel_ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(jTextField_DateOfBirth, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel_ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel_ProfileLayout.createSequentialGroup()
                        .addGroup(jPanel_ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(jTextField_NID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel_ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jTextField_Mobile, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel_ProfileLayout.createSequentialGroup()
                        .addGroup(jPanel_ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jTextField_Gender, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel_ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jTextField_Address, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(30, 30, 30)
                .addGroup(jPanel_ProfileLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton_Edit)
                    .addComponent(jButton_Save))
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_Profile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel_Profile, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane.addTab("Profile", jPanel1);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 51), 2));

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Name:");

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel14.setText("Account No:");

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel15.setText("Available Balance:");

        jLabel16.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel16.setText("Deposite Amount:");

        jTextField_DepositeAmount.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField_DepositeAmount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_DepositeAmountKeyTyped(evt);
            }
        });

        jTextField_DepositeAvailableBalance.setEditable(false);
        jTextField_DepositeAvailableBalance.setBackground(new java.awt.Color(204, 204, 204));
        jTextField_DepositeAvailableBalance.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jTextField_DepositeAccountNo.setEditable(false);
        jTextField_DepositeAccountNo.setBackground(new java.awt.Color(204, 204, 204));
        jTextField_DepositeAccountNo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jTextField_DepositeName.setEditable(false);
        jTextField_DepositeName.setBackground(new java.awt.Color(204, 204, 204));
        jTextField_DepositeName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jButton_DepositeTotal.setText("Total");
        jButton_DepositeTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_DepositeTotalActionPerformed(evt);
            }
        });

        jTextField_DepositeTotal.setEditable(false);
        jTextField_DepositeTotal.setBackground(new java.awt.Color(204, 204, 204));
        jTextField_DepositeTotal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jButton_Deposite.setText("Deposite");
        jButton_Deposite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_DepositeActionPerformed(evt);
            }
        });

        jLabel4.setText("Account No:");

        jButton_DepositeUserSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Search.gif"))); // NOI18N
        jButton_DepositeUserSearch.setText("Search");
        jButton_DepositeUserSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_DepositeUserSearchActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(138, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel14)
                            .addComponent(jLabel15)
                            .addComponent(jLabel16))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_DepositeAvailableBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_DepositeAccountNo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_DepositeName, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jTextField_DepositeAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField_DepositeTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton_DepositeTotal))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField_DepositeUserSearch)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton_DepositeUserSearch)
                        .addGap(91, 91, 91)))
                .addGap(76, 76, 76))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(251, 251, 251)
                .addComponent(jButton_Deposite)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_DepositeUserSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jButton_DepositeUserSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTextField_DepositeName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jTextField_DepositeAccountNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(jTextField_DepositeAvailableBalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(jTextField_DepositeAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_DepositeTotal)
                    .addComponent(jTextField_DepositeTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jButton_Deposite)
                .addContainerGap())
        );

        jTabbedPane.addTab("Deposit", jPanel2);

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 51), 2));

        jLabel17.setText("Account No:");

        jButton_TransferUserSearch.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Search.gif"))); // NOI18N
        jButton_TransferUserSearch.setText("Search");
        jButton_TransferUserSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_TransferUserSearchActionPerformed(evt);
            }
        });

        jLabel18.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel18.setText("Name:");

        jLabel19.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel19.setText("Account No:");

        jLabel20.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel20.setText("Available Balance:");

        jLabel21.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel21.setText("Transfer Amount:");

        jTextField_TransferAmount.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jTextField_TransferAmount.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_TransferAmountKeyTyped(evt);
            }
        });

        jTextField_TransferAvailableBalance.setEditable(false);
        jTextField_TransferAvailableBalance.setBackground(new java.awt.Color(204, 204, 204));
        jTextField_TransferAvailableBalance.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jTextField_TransferAccountNo.setEditable(false);
        jTextField_TransferAccountNo.setBackground(new java.awt.Color(204, 204, 204));
        jTextField_TransferAccountNo.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jTextField_TransferName.setEditable(false);
        jTextField_TransferName.setBackground(new java.awt.Color(204, 204, 204));
        jTextField_TransferName.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jTextField_TransferTotal.setEditable(false);
        jTextField_TransferTotal.setBackground(new java.awt.Color(204, 204, 204));
        jTextField_TransferTotal.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        jButton_TransferTotal.setText("Total");
        jButton_TransferTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_TransferTotalActionPerformed(evt);
            }
        });

        jButton_Transfer.setText("Transfer");
        jButton_Transfer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_TransferActionPerformed(evt);
            }
        });

        jLabel22.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel22.setText("Credit Account No:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Account..." }));

        jTextField_TransferTotal1.setEditable(false);
        jTextField_TransferTotal1.setBackground(new java.awt.Color(204, 204, 204));
        jTextField_TransferTotal1.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(126, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel17)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextField_TransferUserSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(jButton_TransferUserSearch)
                        .addGap(163, 163, 163))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel18)
                            .addComponent(jLabel19)
                            .addComponent(jLabel20)
                            .addComponent(jLabel21)
                            .addComponent(jLabel22))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField_TransferAvailableBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_TransferAccountNo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_TransferName, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jTextField_TransferAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jTextField_TransferTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jButton_TransferTotal))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jTextField_TransferTotal1, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(82, 82, 82))))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(247, 247, 247)
                .addComponent(jButton_Transfer)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_TransferUserSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(jButton_TransferUserSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(jTextField_TransferName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(jTextField_TransferAccountNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jTextField_TransferAvailableBalance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21)
                    .addComponent(jTextField_TransferAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton_TransferTotal)
                    .addComponent(jTextField_TransferTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField_TransferTotal1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton_Transfer)
                .addContainerGap())
        );

        jTabbedPane.addTab("Transfer", jPanel3);

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 51), 2));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 596, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 265, Short.MAX_VALUE)
        );

        jTabbedPane.addTab("Withdraw", jPanel4);

        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 51), 2));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 596, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 265, Short.MAX_VALUE)
        );

        jTabbedPane.addTab("Customer List", jPanel5);

        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 51), 2));

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 596, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 265, Short.MAX_VALUE)
        );

        jTabbedPane.addTab("Transaction", jPanel6);

        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 51), 2));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 596, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 265, Short.MAX_VALUE)
        );

        jTabbedPane.addTab("View Balance", jPanel7);

        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 51), 2));

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 596, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 265, Short.MAX_VALUE)
        );

        jTabbedPane.addTab("Change Pin", jPanel8);

        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 51), 2));

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 596, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 265, Short.MAX_VALUE)
        );

        jTabbedPane.addTab("About", jPanel9);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(83, Short.MAX_VALUE)
                .addComponent(jTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 705, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(116, 116, 116))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField_Date, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jTextField_Date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 82, Short.MAX_VALUE)
                .addComponent(jTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(920, 475));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_EditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_EditActionPerformed
        // TODO add your handling code here:
        jTextField_Address.setEditable(true);
        jTextField_Mobile.setEditable(true);

        jTextField_Address.setBackground(Color.white);
        jTextField_Mobile.setBackground(Color.white);
    }//GEN-LAST:event_jButton_EditActionPerformed

    private void disableTextFields() {
        jTextField_AccountNo.setEditable(false);
        jTextField_AccountType.setEditable(false);
        jTextField_Address.setEditable(false);
        jTextField_DateOfBirth.setEditable(false);
        jTextField_Gender.setEditable(false);
        jTextField_Mobile.setEditable(false);
        jTextField_NID.setEditable(false);
        jTextField_Name.setEditable(false);
        
        jTextField_Address.setBackground(myColor);
        jTextField_Mobile.setBackground(myColor);
    }

    private void ProfileDataLoad(String accNo) {
        try {

            String sql = "SELECT * FROM Account WHERE AccountNo=?";

            pst = conn.prepareStatement(sql);

            pst.setString(1, accNo);

            rs = pst.executeQuery();

            if (rs.next()) {

                jTextField_AccountNo.setText(rs.getString("AccountNo"));
                jTextField_AccountType.setText(rs.getString("AccountType"));
                jTextField_Address.setText(rs.getString("Address"));
                jTextField_DateOfBirth.setText(rs.getString("DateOfBirth"));
                jTextField_Gender.setText(rs.getString("Gender"));
                jTextField_Mobile.setText(rs.getString("Mobile"));
                jTextField_NID.setText(rs.getString("NID"));
                jTextField_Name.setText(rs.getString("Name"));
                jTextField_ProfileUserSearch.setText("");

                disableTextFields();

                rs.close();
                pst.close();
            } else {
                JOptionPane.showMessageDialog(null, "Incorrect Credential");
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);

        } finally {
            try {
                rs.close();
                pst.close();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Something Wrong!");
            }
        }
    }

    private void jButton_ProfileUserSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_ProfileUserSearchActionPerformed
        // TODO add your handling code here:
        ProfileDataLoad(jTextField_ProfileUserSearch.getText());
    }//GEN-LAST:event_jButton_ProfileUserSearchActionPerformed

    private void jButton_SaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_SaveActionPerformed
        // TODO add your handling code here:

        try {

            DBConnect obj = new DBConnect();
            conn = obj.openConnection();

            String mobile = jTextField_Mobile.getText();
            String address = jTextField_Address.getText();
            String acc = jTextField_AccountNo.getText();

            String sql = "UPDATE account SET Mobile = '" + mobile + "', Address = '" + address + "' WHERE AccountNo = '" + acc + "' ";
            pst = conn.prepareStatement(sql);
            pst.execute();
           
            ProfileDataLoad(jTextField_AccountNo.getText());
            
            JOptionPane.showMessageDialog(null, "Profile Updated Successfully.");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_jButton_SaveActionPerformed

    private void jButton_DepositeUserSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_DepositeUserSearchActionPerformed
        // TODO add your handling code here:
        if (jTextField_DepositeUserSearch.getText() != null) {
            try {

                String sql = "SELECT * FROM balances WHERE AccountNo=?";

                pst = conn.prepareStatement(sql);

                pst.setString(1, jTextField_DepositeUserSearch.getText());

                rs = pst.executeQuery();

                if (rs.next()) {

                    jTextField_DepositeAccountNo.setText(rs.getString("AccountNo"));
                    jTextField_DepositeAvailableBalance.setText(rs.getString("Balance"));
                    jTextField_DepositeName.setText(rs.getString("Name"));
                    jTextField_DepositeUserSearch.setText("");

                    rs.close();
                    pst.close();
                } else {
                    JOptionPane.showMessageDialog(null, "Incorrect Credential");
                }

            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);

            } finally {
                try {
                    rs.close();
                    pst.close();
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(null, "Something Wrong!");
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Please Enter Account Number");
        }

    }//GEN-LAST:event_jButton_DepositeUserSearchActionPerformed

    private void onlyNumber(java.awt.event.KeyEvent evt) {
        char iNumber = evt.getKeyChar();
        if (!(Character.isDigit(iNumber))
                || (iNumber == KeyEvent.VK_BACK_SPACE)
                || (iNumber == KeyEvent.VK_DELETE)) {
            evt.consume();
        }
    }

    private void jTextField_DepositeAmountKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_DepositeAmountKeyTyped
        // TODO add your handling code here:
        onlyNumber(evt);
    }//GEN-LAST:event_jTextField_DepositeAmountKeyTyped

    private void jButton_DepositeTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_DepositeTotalActionPerformed
        // TODO add your handling code here:
        try {
            int depositeAmount = Integer.parseInt(jTextField_DepositeAmount.getText().toString());
            int previousBalance = Integer.parseInt(jTextField_DepositeAvailableBalance.getText().toString());
            int total = depositeAmount + previousBalance;
            jTextField_DepositeTotal.setText(String.valueOf(total));
        } catch(Exception e) {
            JOptionPane.showMessageDialog(null, "Please Select User");
        }
    }//GEN-LAST:event_jButton_DepositeTotalActionPerformed

    void account() {
        try {
            String acc = jTextField_DepositeAccountNo.getText();
            String totalBalance = jTextField_DepositeTotal.getText();

            String sql = "UPDATE account SET Balance = '" + totalBalance + "' WHERE AccountNo = '" + acc + "' ";
            pst = conn.prepareStatement(sql);
            pst.execute();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }

    private void jButton_DepositeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_DepositeActionPerformed
        // TODO add your handling code here:
        try {

            DBConnect obj = new DBConnect();
            conn = obj.openConnection();

            String acc = jTextField_DepositeAccountNo.getText();
            String totalBalance = jTextField_DepositeTotal.getText();

            String sql = "UPDATE balances SET Balance = '" + totalBalance + "' WHERE AccountNo = '" + acc + "' ";
            pst = conn.prepareStatement(sql);
            pst.execute();
            account();

            // reseting textfiedsl
            jTextField_DepositeAccountNo.setText("");
            jTextField_DepositeAmount.setText("");
            jTextField_DepositeAvailableBalance.setText("");
            jTextField_DepositeName.setText("");
            jTextField_DepositeTotal.setText("");
            jTextField_DepositeUserSearch.setText("");

            JOptionPane.showMessageDialog(null, "Deposited Successfully.");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Please Select User");
        }

    }//GEN-LAST:event_jButton_DepositeActionPerformed

    private void jButton_TransferUserSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_TransferUserSearchActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_TransferUserSearchActionPerformed

    private void jTextField_TransferAmountKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_TransferAmountKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField_TransferAmountKeyTyped

    private void jButton_TransferTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_TransferTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_TransferTotalActionPerformed

    private void jButton_TransferActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_TransferActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton_TransferActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MyPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MyPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MyPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MyPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MyPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton_Deposite;
    private javax.swing.JButton jButton_DepositeTotal;
    private javax.swing.JButton jButton_DepositeUserSearch;
    private javax.swing.JButton jButton_Edit;
    private javax.swing.JButton jButton_ProfileUserSearch;
    private javax.swing.JButton jButton_Save;
    private javax.swing.JButton jButton_Transfer;
    private javax.swing.JButton jButton_TransferTotal;
    private javax.swing.JButton jButton_TransferUserSearch;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JPanel jPanel_Profile;
    private javax.swing.JTabbedPane jTabbedPane;
    private javax.swing.JTextField jTextField_AccountNo;
    private javax.swing.JTextField jTextField_AccountType;
    private javax.swing.JTextField jTextField_Address;
    private javax.swing.JTextField jTextField_Date;
    private javax.swing.JTextField jTextField_DateOfBirth;
    private javax.swing.JTextField jTextField_DepositeAccountNo;
    private javax.swing.JTextField jTextField_DepositeAmount;
    private javax.swing.JTextField jTextField_DepositeAvailableBalance;
    private javax.swing.JTextField jTextField_DepositeName;
    private javax.swing.JTextField jTextField_DepositeTotal;
    private javax.swing.JTextField jTextField_DepositeUserSearch;
    private javax.swing.JTextField jTextField_Gender;
    private javax.swing.JTextField jTextField_Mobile;
    private javax.swing.JTextField jTextField_NID;
    private javax.swing.JTextField jTextField_Name;
    private javax.swing.JTextField jTextField_ProfileUserSearch;
    private javax.swing.JTextField jTextField_TransferAccountNo;
    private javax.swing.JTextField jTextField_TransferAmount;
    private javax.swing.JTextField jTextField_TransferAvailableBalance;
    private javax.swing.JTextField jTextField_TransferName;
    private javax.swing.JTextField jTextField_TransferTotal;
    private javax.swing.JTextField jTextField_TransferTotal1;
    private javax.swing.JTextField jTextField_TransferUserSearch;
    // End of variables declaration//GEN-END:variables
}
